AllCops:
  Exclude:
    - 'spec/**/*.rb'
    - 'logstash/outputs/domo.rb'
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/AndOr:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/Alias:
  Enabled: false
Lint/ToJSON:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FormatString:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
