# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('com.squareup.okhttp3', 'okhttp', '3.7.0')
require_jar('com.squareup.okhttp3', 'logging-interceptor', '3.7.0')
require_jar('com.google.code.gson', 'gson', '2.8.0')
require_jar('org.jetbrains.kotlin', 'kotlin-stdlib', '1.3.0')
require_jar('org.slf4j', 'slf4j-api', '1.7.21')
require_jar('com.squareup.okio', 'okio', '2.1.0')
require_jar('com.domo', 'domo-java-sdk-all', '0.4.0')
