# encoding: utf-8
require "logstash/outputs/base"
require "logstash/namespace"
require "core_extensions/enumerable/flatten"
require "concurrent"
require "csv"
require "java"
require "redis"
require "redlock"
require "thread"
require "domo/client"
require "domo/queue"
require "logstash-output-domo_jars.rb"

# Add a method to Enumerable to flatten complex data structures
Hash.include CoreExtensions::Enumerable::Flatten

java_import "com.domo.sdk.streams.model.Stream"
java_import "java.util.ArrayList"
java_import "java.util.concurrent.atomic.AtomicReference"

# Write events to a DOMO Streams Dataset.
#
# Requires DOMO OAuth credentials.
# https://developer.domo.com/docs/authentication/overview-4
#
# Additionally, the DOMO Streams API requires that the Dataset and Stream be made via the API.
# Streams cannot be added to existing Datasets.
# https://developer.domo.com/docs/stream/overview
class LogStash::Outputs::Domo < LogStash::Outputs::Base
  config_name "domo"

  concurrency :shared

  # OAuth ClientID
  config :client_id, :validate => :string, :required => :true

  # OAuth Client Secret
  config :client_secret, :validate => :string, :required => :true

  # The DOMO StreamID. If unknown, use the dataset_id parameter instead.
  # This parameter is preferred for performance reasons.
  config :stream_id, :validate => :number

  # The DOMO DataSetID. 
  # Will be used to lookup or create a Stream if the stream_id parameter is not specified.
  config :dataset_id, :validate => :string, :required => :true

  # The hostname for API requests
  config :api_host, :validate => :string, :default => "api.domo.com"

  # Use TLS for API requests
  config :api_ssl, :validate => :boolean, :default => true

  # Retry failed requests. Enabled by default. It would be a pretty terrible idea to disable this. 
  config :retry_failures, :validate => :boolean, :default => true

  # The delay (seconds) on retrying failed requests
  config :retry_delay, :validate => :number, :default => 2.0

  # Use a distributed lock. Necessary when running the plugin against the same Dataset on multiple Logstash servers.
  config :distributed_lock, :validate => :boolean, :default => false

  # The timeout on holding locks in milliseconds.
  # It is not recommended to hold the lock for less than 3,000ms due to lag on the DOMO API.
  config :lock_timeout, :validate => :number, :default => 3000

  # An array of hashes specifying the configuration for the lock servers. Only required if distributed_lock is true.
  #
  # The only required key in the hash is "host", unless the "sentinels" key is provided.
  # If the "sentinels" key is provided, then the "master" key is required.
  # The default redis port (6379) will be used if not provided.
  #
  # An example array with all the accepted keys would be the following:
  # [source,ruby]
  # ----------------------------------
  # lock_servers => [
  #   {
  #     "host"     => "server1"
  #     "port"     => 6379
  #     "password" => "password"
  #   }
  #   {
  #     "host"     => "server2"
  #     "port"     => 6379
  #     "password" => "password2"
  #   }
  #   {
  #     "master"      => "mymaster"
  #     "sentinels" => [
  #       {
  #         "host" => "sentinel1"
  #         "port" => 26379
  #       }
  #     ]
  #   }
  # ]
  # -----------------------
  config :lock_servers, :validate => :array

  # A hash with connection information for the redis client for cached data
  # The hash can contain any arguments accepted by the constructor for the Redis class in the redis-rb gem
  #
  # Below is a sample data structure making use of redis sentinel and a master named "mymaster":
  # [source,ruby]
  # ----------------------------------
  # redis_client => {
  #   "url"       => "redis://mymaster"
  #   "password"  => "password"
  #   "sentinels" => [
  #     {
  #       "host" => "127.0.0.1"
  #       "port" => 26379
  #     }
  #     {
  #       "host" => "sentinel2"
  #       "port" => 26379
  #     }
  #   ]
  # }
  # -----------------------
  #
  # The documentation for the Redis class's constructor can be found at the following URL:
  # https://www.rubydoc.info/gems/redis/Redis#initialize-instance_method
  config :redis_client, :validate => :hash

  # An ID for this instance. Will be autogenerated if not specified.
  config :id, :validate => :string

  attr_accessor :dataset_columns

  public
  def register
    @domo_client = Domo::Client.new(@client_id, @client_secret, @api_host, @api_ssl, Java::ComDomoSdkRequest::Scope::DATA)
    @domo_stream, @domo_stream_execution = @domo_client.stream(@stream_id, @dataset_id, false)
    @dataset_columns = @domo_client.dataset_schema_columns(@domo_stream)

    # Map of batch jobs (per-thread)
    @thread_batch_map = Concurrent::Hash.new

    if @distributed_lock
      if @redis_client.nil?
        raise LogStash::ConfigurationError("The redis_client parameter is required when using distributed_lock")
      else
        @redis_client = symbolize_redis_client_args(@redis_client)
        @redis_client = Redis.new(@redis_client)
      end

      if @lock_servers.nil? or @lock_servers.length <= 0
        raise LogStash::ConfigurationError("The lock_servers parameter is required when using distributed_lock")
      else
        redis_clients = @lock_servers.map do |server|
          # Remove the db key from the server because redlock don't care
          server.delete('db')
          redis_client_from_config(server)
        end
      end

      @lock_manager = Redlock::Client.new(redis_clients)
    end

    if @redis_client.nil?
      @queue = Concurrent::Hash.new
    else
      @queue = Domo::Queue.new(@redis_client, @dataset_id)
    end
  end # def register
  
  public
  # Send Event data using the DOMO Streams API.
  #
  # @param batch [java.util.ArrayList<Domo::Job>, Domo::Queue] The batch of events to send to DOMO.
  def send_to_domo(batch)
    while batch.any?
      if @queue.is_a? Domo::Queue
        failures = Domo::Queue.new(@redis_client, @dataset_id)
      else
        failures = []
      end

      batch.each do |job|
        begin
          @domo_stream_execution = @domo_client.stream_execution(@domo_stream, @domo_stream_execution)
          @domo_client.stream_client.uploadDataPart(@domo_stream.getId, @domo_stream_execution.getId, job.part_num, job.data)
          puts job.part_num
        rescue Java::ComDomoSdkRequest::RequestException => e
          if e.getStatusCode == -1 || (e.getStatusCode < 400 && e.getStatusCode >= 500)
            unless @domo_stream_execution.nil?
              @domo_stream_execution = @domo_client.stream_execution(@domo_stream, @domo_stream_execution)
            end

            if @retry_failures
              @logger.info("Got a retriable error from the DOMO Streams API.",
                           :code => e.getStatusCode,
                           :exception => e,
                           :event => job.event,
                           :data => job.data)

              failures << job
            else
              @logger.error("Encountered a fatal error interacting with the DOMO Streams API.",
                            :code => e.getStatusCode,
                            :exception => e,
                            :data => data,
                            :event => event)
            end
          # TODO: Implement DLQ?
          else
            @logger.error("Encountered a fatal error interacting with the DOMO Streams API.",
                          :code => e.getStatusCode,
                          :exception => e,
                          :data => data,
                          :event => event)
          end
        end
      end
      
      if failures.empty?
        unless @domo_stream_execution.nil?
          # Commit and create a new Stream Execution if that hasn't happened already
          @domo_stream_execution = @domo_client.stream_client.getExecution(@domo_stream.getId, @domo_stream_execution.getId)
          if @domo_stream_execution.currentState == "ACTIVE"
            @domo_client.stream_client.commitExecution(@domo_stream.getId, @domo_stream_execution.getId)
            @domo_stream_execution = nil
          end
        end

        unless @redis_client.nil?
          _ = @redis_client.getset("#{@dataset_id}_part_num", "0")
        end

        break
      end

      if @retry_failures
        batch = failures
        @logger.info("Retrying DOMO Streams API requests. Will sleep for #{@retry_delay} seconds")
        sleep(@retry_delay)
      end
    end
  end

  public
  def close
    # Commit or abort the stream execution if that hasn't happened already
    unless @domo_stream_execution.nil?
      @domo_stream_execution = @domo_client.stream_client.getExecution(@domo_stream.getId, @domo_stream_execution.getId)

      if @domo_stream_execution.currentState == "ACTIVE"
        @domo_client.stream_client.commitExecution(@domo_stream.getId, @domo_stream_execution.getId)
      elsif @domo_stream_execution.currentState == "ERROR" or @domo_stream_execution.currentState == "FAILED"
        @domo_client.stream_client.abortExecution(@domo_stream.getId, @domo_stream_execution.getId)
      end

      unless @redis_client.nil?
        _ = @redis_client.getset("#{@dataset_id}_part_num", "0")
      end
    end
  end

  public
  def multi_receive(events)
    if @redis_client.nil?
      cur_thread = Thread.current

      if @queue.include? cur_thread
        queue = @queue[cur_thread]
      else
        @queue[cur_thread] = ArrayList.new(events.size)
        queue = @queue[cur_thread]
      end
    else
      queue = @queue
    end

    if @redis_client.nil?
      part_num = java.util.concurrent.atomic.AtomicInteger.new(1)
    end
    events.each do |event|
      break if event == LogStash::SHUTDOWN

      # Set the Streams API Data Part Number
      unless @redis_client.nil?
        part_num = @redis_client.incr("#{@dataset_id}_part_num")
      end

      # Encode the Event data and add a job to the queue
      data = encode_event_data(event)
      job = Domo::Job.new(event, data, part_num)
      queue.add(job)

      if @redis_client.nil?
        part_num.incrementAndGet
      end
    end

    batch = queue
    if batch.any?
      send_to_domo(batch)
      if @redis_client.nil?
        batch.clear
        part_num.set(1)
      end
    end
  end

  private
  # Build a Redis client from hash entries passed by our configuration variables (lock_servers and redis_client)
  #
  # @param server [Hash] An individual server entry in the configuration variable
  # @return [Redis]
  def redis_client_from_config(server)
    password = server.fetch('password', nil)
    sentinels = server.fetch('sentinels', nil)
    db = server.fetch('db', nil)

    if sentinels.nil?
      host = server['host']
      port = server.fetch('port', 6379)

      if db.nil?
        Redis.new(host: host, port: port, password: password)
      else
        Redis.new(host: host, port: port, password: password, db: db)
      end
    else
      url = "redis://#{server['master']}"

      if db.nil?
        Redis.new(url: url, password: password, sentinels: sentinels)
      else
        Redis.new(url: url, password: password, sentinels: sentinels, db: db)
      end
    end
  end

  private
  # CSV encode event data to pass to DOMO
  #
  # @param event [LogStash::Event] The Event to be sent to DOMO.
  # @return [String] The CSV encoded string.
  def encode_event_data(event)
    encode_options = {
        :headers => @dataset_columns,
        :write_headers => false,
        :return_headers => false,
    }

    csv_data = CSV.generate(String.new, encode_options) do |csv_obj|
      data = event.to_hash.flatten_with_path
      data = data.select { |k, _| @dataset_columns.include? k }
      @dataset_columns.each do |col|
        unless data.has_key? col
          data[col] = nil
        end
      end

      data = data.sort_by { |k, _| @dataset_columns.index(k) }.to_h
      csv_obj << data.values
    end
    csv_data.strip
  end

  private
  # Builds an array of Redis clients out of the plugin's configuration parameters for distributed locking
  #
  # @return [Array<Redis>]
  def lock_servers(lock_hosts, lock_ports, lock_passwords)
    lock_servers = Array.new
    lock_hosts.each_with_index do |host, i|
      port = lock_ports.fetch(i, 6379)
      password = lock_passwords.fetch(i, nil)

      lock_servers << Redis.new("host" => host, "port" => port, "password" => password)
    end

    lock_servers
  end

  private
  # Convert all keys in the redis_client hash to symbols because that's how redis-rb wants them.
  #
  # @param redis_client_args [Hash]
  # @return [Hash]
  def symbolize_redis_client_args(redis_client_args)
    redis_client_args = redis_client_args.inject({}) {|memo, (k, v)| memo[k.to_sym] = v; memo}
    unless redis_client_args.fetch(:sentinels, nil).nil?

      redis_client_args[:sentinels] = redis_client_args[:sentinels].map do |sentinel|
        sentinel.inject({}) {|memo, (k, v)| memo[k.to_sym] = v; memo}
      end
    end

    redis_client_args
  end
end # class LogStash::Outputs::Domo
